name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  CI:
    name: Continuous Integration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 23.x

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # Pode ser 'zulu', 'adopt', entre outros.
          java-version: '17'

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: npm test
  
  CD: 
    name: Continuous Delivery
    runs-on: ubuntu-latest

    needs: CI

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 23.x

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          packager: npm
          token: ${{ secrets.EAS_EXPO_TOKEN }}
      
      - name: Get config file
        env: 
          GOOGLE_SERVICES_64: ${{ secrets.EAS_GOOGLE_PLAY_API }}
        run: |
          echo $GOOGLE_SERVICES_64 > google-services.json.b64
          base64 -d -i google-services.json.b64 > google-services.json

      - name: Build and Submit
        run: eas build --platform android --profile production --non-interactive --auto-submit-with-profile=preview --no-wait